In [4]:
import pandas as pd

In [5]:
df = pd.read_excel(
    r"C:\Users\NIHAR\Desktop\DS_projects\Genai_projects\quickhyre assessment\nihar-nandala-genar-challenge\data\Bisoprolol_icsr_sample_1068rows.xlsx"
)

df.shape

(1068, 67)

In [6]:
pd.set_option("display.max_columns", None)

df.head()

,safetyreportversion,safetyreportid,primarysourcecountry,occurcountry,transmissiondateformat,transmissiondate,reporttype,serious,seriousnessdeath,seriousnesslifethreatening,seriousnesshospitalization,seriousnessdisabling,seriousnesscongenitalanomali,seriousnessother,receivedateformat,receivedate,receiptdateformat,receiptdate,fulfillexpeditecriteria,companynumb,primarysource_reportercountry,primarysource_qualification,sender_sendertype,sender_senderorganization,receiver_receivertype,receiver_receiverorganization,patient_patientonsetage,patient_patientonsetageunit,patient_patientsex,patient_reaction_reactionmeddraversionpt,patient_reaction_reactionmeddrapt,patient_reaction_reactionoutcome,patient_drug_drugcharacterization,patient_drug_medicinalproduct,patient_drug_drugauthorizationnumb,patient_drug_drugstructuredosagenumb,patient_drug_drugstructuredosageunit,patient_drug_drugseparatedosagenumb,patient_drug_drugintervaldosageunitnumb,patient_drug_drugintervaldosagedefinition,patient_drug_drugdosagetext,patient_drug_drugdosageform,patient_drug_drugadministrationroute,patient_drug_drugindication,patient_drug_actiondrug,patient_drug_drugadditional,patient_drug_activesubstance_activesubstancename,patient_summary_narrativeincludeclinical,drugs,report_date,patient_patientweight,patient_drug_drugstartdateformat,patient_drug_drugstartdate,patient_drug_drugenddateformat,patient_drug_drugenddate,patient_drug_drugtreatmentduration,patient_drug_drugtreatmentdurationunit,patient_drug_drugcumulativedosagenumb,patient_drug_drugcumulativedosageunit,primarysource_literaturereference,duplicate,reportduplicate_duplicatesource,reportduplicate_duplicatenumb,patient_drug_drugrecurreadministration,patient_drug_drugbatchnumb,patient_patientagegroup,authoritynumb
0,1,24780403,italy,italy,102,20250115,spontaneous report,serious,no,no,yes,no,no,yes,102,20241227,102,20241227,yes,IT-MINISAL02-1015898,italy,pharmacist,pharmaceutical company,AUROBINDO,other,FDA,85.0,year,female,"27.1,27.1","Rectal haemorrhage,Deficiency anaemia","unknown,unknown","suspect,concomitant,concomitant,concomitant,co...","CLOPIDOGREL BISULFATE,PANTOPRAZOLE SODIUM,PRED...",90540,"75,20,5,500,2.5,250,500,15,300,50","mg,mg,mg,mg,mg,mg,mg,mg,mg,mg","1,1,1,1,2,2,1,1,1","1,1,1,1,1,1,1,1,1","month,month,month,month,month,month,month,mont...","75 MILLIGRAM, ONCE A DAY (IN THE MORNING),20 M...","Film-coated tablet,Tablet,Tablet,Tablet,Tablet...","oral,oral,oral,oral,oral,oral,oral,transmammar...","Arterial thrombosis,Gastrooesophageal reflux d...","unknown,unknown,unknown,unknown,unknown,unknow...","placebo,placebo,placebo,placebo,placebo,placeb...","CLOPIDOGREL BISULFATE,PANTOPRAZOLE SODIUM,PRED...",CASE EVENT DATE: 20241130,"ALLOPURINOL,BISOPROLOL FUMARATE,CLOPIDOGREL BI...",2024-12-27,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,24780599,france,france,102,20250115,spontaneous report,serious,no,no,yes,no,no,yes,102,20241227,102,20241227,yes,FR-AFSSAPS-RE2024001239,france,physician,pharmaceutical company,AUROBINDO,other,FDA,69.0,year,female,27.1,Coma,recovered/resolved,"suspect,suspect,suspect,suspect","DULOXETINE,BISOPROLOL,ALPRAZOLAM,ROPINIROLE","090778,77910,090871,200462",NaN,NaN,"1,1,1,1","1,1,1,1","month,month,month,month","UNK UNK, ONCE A DAY,UNK, ONCE A DAY,UNK, ONCE ...",NaN,"oral,oral,oral,oral","Product used for unknown indication,Product us...","drug withdrawn,drug withdrawn,drug withdrawn,d...","test drug,test drug,test drug,test drug","DULOXETINE,BISOPROLOL,ALPRAZOLAM,ROPINIROLE",CASE EVENT DATE: 20240711,"ALPRAZOLAM,BISOPROLOL,DULOXETINE,ROPINIROLE",2024-12-27,62.0,102102102102,"20240711,20240711,20240711,20240711",102102102102,"20240711,20240711,20240711,20240711","1,1,1,1","day,day,day,day",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,24780680,france,france,102,20250114,spontaneous report,serious,no,no,yes,no,no,yes,102,20241227,102,20241227,yes,FR-AFSSAPS-AN2024001706,france,physician,pharmaceutical company,AUROBINDO,other,FDA,85.0,year,male,27.1,Acute kidney injury,recovered/resolved,"suspect,suspect,suspect,concomitant,concomitan...","AMOXICILLIN,IOBITRIDOL,PRADAXA,LEVOFLOXACIN,LE...",65256,"12,90,2,500,750,500,3,20,1.25,2,20,1,3,1,2","g,iu,dosage form,mg,mg,mg,mg/kg,mg,mg,dosage f...","1,1,1,1,2,1,1,1,1,1,1,1","1,1,1,1,1,1,1,1,1,1,1,1","month,month,month,month,month,month,month,mont...","12 GRAM, ONCE A DAY,90 MILLILITER, 1 TOTAL,2 D...","Injectable Solution,Capsule,Injectable Solutio...","intravenous,intravenous,oral,oral,oral,oral,in...","Infection,Computerised tomogram,Cardiovascular...","drug withdrawn,not applicable,drug withdrawn,d...","test drug,comparator,test drug,test drug,test ...","AMOXICILLIN,IOBITRIDOL,DABIGATRAN ETEXILATE ME...",CASE EVENT DATE: 20240915,"ACETAMINOPHEN,AMOXICILLIN,BISOPROLOL FUMARATE,...",2024-12-27,62.0,"102,102,102,102,102,102,102,102,102,102","20240910,20240913,20240911,20240912,20240917,2...","102,102,102,102,102,102,102,102,102,102,102,10...","20240917,20240913,20240917,20240911,20240917,2...","7,1,1,5,36,1,1,43,3,1","day,day,day,day,day,day,day,day,day,day","63,3000,3000,3000,17.591,5,5","002,003,003,003,002,032,032",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,24784771,united kingdom,united kingdom,102,20250114,spontaneous report,serious,no,no,no,no,no,yes,102,20241228,102,20241228,yes,GB-MHRA-MIDB-7db13c72-ddb6-4926-a31d-d3b72b5e657d,united kingdom,pharmacist,pharmaceutical company,AUROBINDO,other,FDA,86.0,year,female,27.1,Muscle spasms,recovered/resolved,"suspect,concomitant,concomitant,concomitant,co...","LOSARTAN,BISOPROLOL,DAPAGLIFLOZIN,EDOXABAN,FAM...",90083,NaN,NaN,NaN,NaN,NaN,"UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK,UNK",NaN,"vaginal,vaginal,vaginal,vaginal,vaginal,vagina...","Product used for unknown indication,Product us...","unknown,unknown,unknown,unknown,unknown,unknow...","placebo,placebo,placebo,placebo,placebo,placeb...","LOSARTAN,BISOPROLOL,DAPAGLIFLOZIN,EDOXABAN,FAM...",NaN,"ACETAMINOPHEN,BISOPROLOL,DAPAGLIFLOZIN,EDOXABA...",2024-12-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,24784845,united kingdom,united kingdom,102,20250114,spontaneous report,serious,no,no,no,yes,no,yes,102,20241228,102,20241228,yes,GB-MHRA-MED-202412141853384010-TCVSF,united kingdom,consumer or non-health professional,pharmaceutical company,AUROBINDO,other,FDA,35.0,year,male,"27.1,27.1,27.1","Chest pain,Anxiety,Panic attack","not recovered/not resolved/ongoing,recovering/...","suspect,concomitant","AMLODIPINE,BISOPROLOL",78021,100,mg,NaN,NaN,NaN,"100 MILLIGRAM, DAILY IN MORNING,UNK",Tablet,"vaginal,vaginal","Hypertension,Hypertension","drug withdrawn,unknown","test drug,placebo","AMLODIPINE BESYLATE,BISOPROLOL",CASE EVENT DATE: 20241115,"AMLODIPINE,BISOPROLOL",2024-12-28,109.0,102102,"20241108,20241108",102,20241207,1,minute,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
print("total rows:",len(df))
print("unique_cases:",df["safetyreportid"].nunique())

total rows: 1068
unique_cases: 1024

In [8]:
df["duplicate"].value_counts()

duplicate
1.0    218
Name: count, dtype: int64

In [9]:
df["duplicate"].value_counts(dropna=False)

duplicate
NaN    850
1.0    218
Name: count, dtype: int64

In [11]:
df["safetyreportversion"].value_counts(dropna=False)

safetyreportversion
1    865
2    124
3     45
4     18
5      6
6      5
8      3
7      2
Name: count, dtype: int64

In [21]:
version_counts=df.groupby("safetyreportid")["safetyreportversion"].nunique()
print(version_counts.max())
print(version_counts[version_counts>1].shape[0])

3
41

In [19]:
print(version_counts[version_counts>1].shape[0])

41

In [20]:
version_counts.max()

3

In [23]:
max_version = df.groupby("safetyreportid")["safetyreportversion"].transform("max")
df_latest = df[df["safetyreportversion"]==max_version].copy()

print(df_latest.shape)
print(df_latest["safetyreportid"].nunique())

(1024, 67)
1024

In [25]:
df_latest.shape

(1024, 67)

In [27]:
col = df_latest['patient_reaction_reactionmeddrapt']

In [28]:
col.astype(str).str.contains(',', regex=False).sum()

646

In [30]:
df_latest["serious"].value_counts()

serious
serious        1023
not serious       1
Name: count, dtype: int64

In [6]:
import sys
import pandas as pd
sys.path.append("../src")
from data_prep import clean_data
from analysis import case_volume

raw_df = pd.read_excel("../data/Bisoprolol_icsr_sample_1068rows.xlsx")
cleaned = clean_data(raw_df)
result = case_volume(cleaned)
print(result)

{'total_cases': 1024, 'serious_cases': 1023, 'non_serious_cases': 1, 'serious_pct': 99.9}

In [6]:
pd.set_option("display.max_rows", None)

df["patient_patientonsetage"].value_counts()

patient_patientonsetage
79.0     38
73.0     34
66.0     33
74.0     32
76.0     31
68.0     30
77.0     30
78.0     29
72.0     29
71.0     28
75.0     28
82.0     26
67.0     25
83.0     25
70.0     25
84.0     24
69.0     24
86.0     24
64.0     24
85.0     21
60.0     20
80.0     19
65.0     18
63.0     18
61.0     18
89.0     17
56.0     17
88.0     16
87.0     16
81.0     16
93.0     15
91.0     15
59.0     15
54.0     14
90.0     14
57.0     12
53.0     12
62.0     11
55.0     10
58.0      9
50.0      7
44.0      7
52.0      7
39.0      6
48.0      6
51.0      5
46.0      5
92.0      4
41.0      4
15.0      4
33.0      3
49.0      3
42.0      3
95.0      3
45.0      3
94.0      3
43.0      2
2.0       2
29.0      2
37.0      2
99.0      2
38.0      2
27.0      2
4.0       2
40.0      2
22.0      2
3.0       2
1.0       1
28.0      1
24.0      1
31.0      1
36.0      1
13.0      1
9.0       1
32.0      1
23.0      1
6.0       1
35.0      1
96.0      1
34.0      1
20.0      1
98.0      1
7.0       1
104.0     1
17.0      1
47.0      1
19.0      1
Name: count, dtype: int64

In [7]:
df["patient_patientonsetageunit"].value_counts()

patient_patientonsetageunit
year     975
month      5
day        3
800        3
week       1
Name: count, dtype: int64

In [8]:
df.loc[
    df["patient_patientonsetageunit"] != "year",
    ["patient_patientonsetage", "patient_patientonsetageunit"]
].value_counts()

patient_patientonsetage  patient_patientonsetageunit
2.0                      month                          2
1.0                      month                          1
3.0                      800                            1
                         month                          1
7.0                      800                            1
9.0                      800                            1
29.0                     week                           1
73.0                     day                            1
93.0                     month                          1
Name: count, dtype: int64

In [11]:
from data_prep import add_age_columns
df_with_age = add_age_columns(cleaned)

In [12]:
df_with_age["age_group"].value_counts()

age_group
75+         408
65-74       266
18-64       248
unknown      86
under 18     16
Name: count, dtype: int64

In [15]:
cleaned.loc[
    cleaned["patient_patientonsetageunit"] != "year",
    ["patient_patientonsetage", "patient_patientonsetageunit"]
].value_counts()

patient_patientonsetage  patient_patientonsetageunit
2.0                      month                          2
1.0                      month                          1
3.0                      800                            1
                         month                          1
7.0                      800                            1
9.0                      800                            1
29.0                     week                           1
73.0                     day                            1
93.0                     month                          1
Name: count, dtype: int64

In [16]:
df_with_age[
    (df_with_age["patient_patientonsetage"] == 93) &
    (df_with_age["patient_patientonsetageunit"].str.lower() == "month")
][[
    "patient_patientonsetage",
    "patient_patientonsetageunit",
    "age_years",
    "age_group"
]]

     patient_patientonsetage patient_patientonsetageunit  age_years age_group
417                     93.0                       month       7.75  under 18

In [17]:
df_with_age["patient_patientonsetage"].isna().sum()

83

In [18]:
df_with_age[
    df_with_age["age_group"]=="unknown"
][[
    "patient_patientonsetage",
    "patient_patientonsetageunit",
    "age_years",
    "age_group"
]].to_string()

'      patient_patientonsetage patient_patientonsetageunit  age_years age_group\n14                        NaN                         NaN        NaN   unknown\n15                        NaN                         NaN        NaN   unknown\n33                        NaN                         NaN        NaN   unknown\n65                        NaN                         NaN        NaN   unknown\n72                        NaN                        year        NaN   unknown\n85                        NaN                        year        NaN   unknown\n115                       NaN                         NaN        NaN   unknown\n117                       NaN                         NaN        NaN   unknown\n118                       NaN                        year        NaN   unknown\n126                       NaN                        year        NaN   unknown\n146                       NaN                         NaN        NaN   unknown\n157                       NaN                         NaN        NaN   unknown\n158                       NaN                         NaN        NaN   unknown\n168                       NaN                         NaN        NaN   unknown\n190                       NaN                         NaN        NaN   unknown\n201                       NaN                         day        NaN   unknown\n216                       NaN                         NaN        NaN   unknown\n236                       NaN                         NaN        NaN   unknown\n246                       NaN                        year        NaN   unknown\n280                       NaN                         NaN        NaN   unknown\n282                       NaN                         NaN        NaN   unknown\n297                       NaN                         NaN        NaN   unknown\n334                       NaN                         NaN        NaN   unknown\n340                       NaN                         NaN        NaN   unknown\n349                       NaN                         NaN        NaN   unknown\n370                       NaN                         NaN        NaN   unknown\n385                       NaN                        year        NaN   unknown\n412                       NaN                         NaN        NaN   unknown\n419                       NaN                         NaN        NaN   unknown\n436                       NaN                        year        NaN   unknown\n440                       7.0                         800        NaN   unknown\n443                       NaN                         NaN        NaN   unknown\n450                       NaN                         NaN        NaN   unknown\n453                       NaN                        year        NaN   unknown\n485                       NaN                         NaN        NaN   unknown\n491                       NaN                         day        NaN   unknown\n502                       NaN                         NaN        NaN   unknown\n509                       NaN                         NaN        NaN   unknown\n513                       NaN                         NaN        NaN   unknown\n550                       NaN                         NaN        NaN   unknown\n564                       NaN                         NaN        NaN   unknown\n567                       NaN                         NaN        NaN   unknown\n595                       NaN                         NaN        NaN   unknown\n610                       NaN                         NaN        NaN   unknown\n611                       NaN                         NaN        NaN   unknown\n623                       NaN                         NaN        NaN   unknown\n641                       NaN                         NaN        NaN   unknown\n658                       NaN                         NaN        NaN   unknown\n662                       NaN                         NaN        NaN   unknown\n666                       NaN                         NaN        NaN   unknown\n688                       9.0                         800        NaN   unknown\n709                       3.0                         800        NaN   unknown\n748                       NaN                         NaN        NaN   unknown\n751                       NaN                         NaN        NaN   unknown\n765                       NaN                         NaN        NaN   unknown\n779                       NaN                         NaN        NaN   unknown\n780                       NaN                         NaN        NaN   unknown\n783                       NaN                         NaN        NaN   unknown\n788                       NaN                         NaN        NaN   unknown\n789                       NaN                         NaN        NaN   unknown\n800                       NaN                         NaN        NaN   unknown\n805                       NaN                         NaN        NaN   unknown\n815                       NaN                         NaN        NaN   unknown\n826                       NaN                         NaN        NaN   unknown\n838                       NaN                         NaN        NaN   unknown\n857                       NaN                         NaN        NaN   unknown\n859                       NaN                         NaN        NaN   unknown\n865                       NaN                         NaN        NaN   unknown\n870                       NaN                         NaN        NaN   unknown\n875                       NaN                         NaN        NaN   unknown\n878                       NaN                         NaN        NaN   unknown\n879                       NaN                         NaN        NaN   unknown\n884                       NaN                         NaN        NaN   unknown\n886                       NaN                         NaN        NaN   unknown\n889                       NaN                         NaN        NaN   unknown\n923                       NaN                         NaN        NaN   unknown\n927                       NaN                         NaN        NaN   unknown\n928                       NaN                         NaN        NaN   unknown\n934                       NaN                         NaN        NaN   unknown\n958                       NaN                         NaN        NaN   unknown\n980                       NaN                         NaN        NaN   unknown\n982                       NaN                         NaN        NaN   unknown\n1022                      NaN                         NaN        NaN   unknown\n1033                      NaN                         NaN        NaN   unknown\n1054                      NaN                         NaN        NaN   unknown\n1063                      NaN                         NaN        NaN   unknown'

In [19]:
df_with_age[
    df_with_age["age_group"] == "unknown"
].groupby(
    ["patient_patientonsetage", "patient_patientonsetageunit"],
    dropna=False
).size().sort_values(ascending=False)

patient_patientonsetage  patient_patientonsetageunit
NaN                      NaN                            73
                         year                            8
                         day                             2
3.0                      800                             1
7.0                      800                             1
9.0                      800                             1
dtype: int64

In [3]:
import pandas as pd
from data_prep import clean_data
from analysis import case_volume
raw_df = pd.read_excel("../data/Bisoprolol_icsr_sample_1068rows.xlsx")
cleaned = clean_data(raw_df)
result = case_volume(cleaned)
print(result)
cleaned["age_group"].value_counts()

{'total_cases': 1024, 'serious_cases': 1023, 'non_serious_cases': 1, 'serious_pct': 99.9}

age_group
75+         408
65-74       266
18-64       248
unknown      86
under 18     16
Name: count, dtype: int64

In [11]:
same = (
    (cleaned["primarysourcecountry"] == cleaned["occurcountry"]) &
    (cleaned["primarysourcecountry"] == cleaned["primarysource_reportercountry"])
)

print(same.value_counts())

True     1016
False       8
Name: count, dtype: int64

In [12]:
cleaned.loc[~same, [
    "primarysourcecountry",
    "occurcountry",
    "primarysource_reportercountry"
]]

    primarysourcecountry   occurcountry primarysource_reportercountry
789               canada            NaN                        canada
793       united kingdom            NaN                united kingdom
798                   eu            NaN                            eu
805       united kingdom            NaN                united kingdom
819                   eu  united states                            eu
848       united kingdom            NaN                united kingdom
947        united states            NaN                 united states
959                   eu            NaN                            eu

In [14]:
cleaned["patient_patientsex"].value_counts(dropna=False)

patient_patientsex
female    503
male      493
NaN        28
Name: count, dtype: int64

In [1]:
import pandas as pd
from analysis import demographics,case_volume
from data_prep import clean_data

raw_df = pd.read_excel("../data/Bisoprolol_icsr_sample_1068rows.xlsx")
cleaned=clean_data(raw_df)
result = demographics(cleaned)

In [ ]:
print(result)

{'total_cases_by_age_group': age_group
18-64       248
65-74       266
75+         408
under 18     16
unknown      86
Name: safetyreportid, dtype: int64, 'total_cases_by_sex': patient_patientsex
female     503
male       493
unknown     28
Name: safetyreportid, dtype: int64, 'total_cases_by_country': occurcountry
FI                  1
HR                  2
IE                  3
RO                  2
SA                  2
UA                  2
australia           1
belgium             2
canada             55
china               1
eu                342
france            185
germany            33
indonesia           1
italy              51
poland             18
portugal            8
spain              24
sweden              2
united kingdom    278
united states       4
unknown             7
Name: safetyreportid, dtype: int64}

In [6]:
short_codes = cleaned[cleaned["occurcountry"].str.len() == 2]
print(short_codes[["occurcountry", "primarysource_reportercountry","primarysourcecountry"]])

     occurcountry primarysource_reportercountry primarysourcecountry
24             IE                            IE                   IE
171            RO                            RO                   RO
317            RO                            RO                   RO
322            SA                            SA                   SA
325            SA                            SA                   SA
...           ...                           ...                  ...
1063           eu                            eu                   eu
1064           eu                            eu                   eu
1065           eu                            eu                   eu
1066           eu                            eu                   eu
1067           eu                            eu                   eu

[354 rows x 3 columns]

In [9]:
print(sorted(cleaned["occurcountry"].dropna().unique()))

['FI', 'HR', 'IE', 'RO', 'SA', 'UA', 'australia', 'belgium', 'canada', 'china', 'eu', 'france', 'germany', 'indonesia', 'italy', 'poland', 'portugal', 'spain', 'sweden', 'united kingdom', 'united states']